include: package:pedantic/analysis_options.yaml

#https://dart-lang.github.io/linter/lints/
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - lib/*.g.dart
    - lib/**/*.g.dart
  errors:
    always_declare_return_types: warning
    camel_case_types: warning
    empty_constructor_bodies: warning
    annotate_overrides: warning
    avoid_init_to_null: warning
    type_annotate_public_apis: warning
    type_init_formals: warning
    sort_unnamed_constructors_first: warning
    unnecessary_brace_in_string_interps: warning
    prefer_void_to_null: warning
    unnecessary_await_in_return: warning
    use_to_and_as_if_applicable: warning
    valid_regexps: warning
    throw_in_finally: warning
    use_full_hex_values_for_flutter_colors: warning
    use_function_type_syntax_for_parameters: warning
    use_rethrow_when_possible: warning
    use_setters_to_change_properties: warning
    use_string_buffers: warning
    unused_import: warning
    unused_local_variable: warning
    prefer_final_locals: warning

linter:
  rules:
    - camel_case_types
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_return_types_on_setters
    - avoid_slow_async_io
    - avoid_unused_constructor_parameters
    - await_only_futures
    - cancel_subscriptions
    - cascade_invocations
    - control_flow_in_finally
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - invariant_booleans
    - iterable_contains_unrelated_type
    - join_return_with_assignment
    - library_names
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - non_constant_identifier_names
    - library_prefixes
    - only_throw_errors
    - package_names
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_contains
    - prefer_final_fields
    - prefer_final_locals
    - prefer_foreach
    - prefer_initializing_formals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - prefer_typing_uninitialized_variables
    - recursive_getters
    - slash_for_doc_comments
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - type_annotate_public_apis
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_statements
    - unnecessary_new
    - unnecessary_this
    - lines_longer_than_80_chars
    - unrelated_type_equality_checks
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable
    - valid_regexps
    - sort_child_properties_last
    - prefer_conditional_assignment